-- 1 Задание
SELECT TrackId, Composer from Track

where TrackId = 51;


-- 2 Задание
SELECT * from Track

ORDER BY Name

Limit 52-48 OFfset 48;


-- 3 Задание
SELECT * from Track

where Name like '%Hit%';


-- 4 Задание
SELECT * from Track

where Milliseconds BETWEEN 1000*350 and 1000*360;


-- 5 Задание

-- 6 Задание
SELECT * from Track

where AlbumId = 108;


-- 7 Задание

-- 8 Задание
SELECT * from Track

ORDER BY UnitPrice DESc, UnitPrice

limit 1;


-- 9 Задание

-- 10 Задание

-- 11 Задание

-- 12 Задание

-- 13 Задание
